### ISSUE TITLE
64-bit support request for iOS

### ISSUE THREAD

**Issue by svyatoslav-zubrin** [gerasim13/Dirac-3-LE#3]
Hello, 
our app uses the library but from now Apple requires 64-bit support and current version of the library doesn't have it. Is it possible for you to update/rebuild the library?
Thanks.

**Comment by gerasim13** [comment]
Hello. This is unofficial Dirac-3 repository. Please send your questions to author of library (http://www.zynaptiq.com/ztx/)
I'm no longer use this library.
Take a look to superpowered sdk (http://superpowered.com/), this library contains pitchshifter.

**Comment by svyatoslav-zubrin** [comment]
Git it, thanks for the quick reply.
